const SWITCH_THEME = 'SWITCH_THEME'
const SAVE_TRACKS = 'SAVE_TRACKS'
const SAVE_CONTROL_FUN = 'SAVE_CONTROL_FUN'
const SAVE_CURR_TRACK_IND = 'SAVE_CURR_TRACK_IND'

export {SWITCH_THEME, SAVE_TRACKS, SAVE_CONTROL_FUN, SAVE_CURR_TRACK_IND}